# Generated by Django 5.1.6 on 2025-12-03 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.BooleanField(default=False, help_text='Is the task a priority?'),
        ),
    ]
